[gst_pipeline_device] ; dev12 введите любой pipeline, оканчивающийся ! appsink name=sink ...
; RTP CLIENT EXAMPLE PIPELINE:
src = rtspsrc location=rtsp://192.168.144.103:8554/live/track0 latency=10 ! queue ;
; src = rtspsrc location=rtsp://192.168.144.101/554 latency=10 ! queue ;
; src = udpsrc port=8001 caps = "application/x-rtp, media=(string)video" ;
bin = rtph264depay request-keyframe=true ! h264parse config-interval=1 ! avdec_h264 ! videoconvert ;
sink = video/x-raw, format=BGR ! appsink name=sink emit-signals=true ;

[NETWORK] ;
send_ip = 192.168.144.103 ; 192.168.1.160 ; 192.168.1.160 ; ip для отправки команд по UDP (160 для Сазан - земля)
client_receive_telemetry_port = 30000 ; Порт для получения телеметрии от goen
goen_send_commands_port = 30000 ; Порт для отправки команд на goen

[tracking] ; Параметры для алгоритма TracShats:
zahvat_size_TV = 64 ; Размер ширины стороны квадратной рамки захвата, при 0 - выделение рамки мышкой.
zahvat_size_TPV = 36 ;

[main_settings] ; Выбор типа алгоритма:
device_id = 12 ; идентификатор устройства, с которого считываются кадры:
; 0 - FOLDER,
; 12 - GST_PIPELINE_DEVICE
parallel = 1 ; режим параллельного исполнения трекера и приема кадров от device
show_win = 0;

[logger]
lavel = 2 ; 0 - логирование отключено ; 1 - немелденное логгирование ; 2 - интервальное логгирование
destination = 0 ; 0 - логирование только в терминал ; 1 - запись логов только в файл ; 2 логирование в терминал + запись в файл
sleep_ms = 3000 ; интервал в мс
path_to_log = ../log ; путь к папке с логгами
max_number_of_log_folder = 2 ; максиёмальное количество папок с логами
log_current_time = 0 ; вкл/выкл логирования текущей даты и времени
log_execution_time = 1 ; вкл/выкл логирования времени выполнения программы
log_cpu_temperature = 1 ; вкл/выкл логирования времени температуры CPU
log_gpu_temperature = 0 ; вкл/выкл логирования времени температуры GPU

[demonstration_settings]
frame_show_width = 1920 ; ширина отображаемого кадра
demonstration_mode = 3 ; режим отображения: 1 - рамка захвата объекта, дополнительно: 2 - рамка поиска, 3 - статус трекера, 4 - размеры рамки объекта.

; Devices ;
[folder] ; dev0 (FOLDER)
way2init_rect = ../img_et/way2init_rect7.txt ; Путь к файлу с данными первоначального квадрата.
fps = 25 ;
frame_w = 0 ;
frame_h = 0 ;
path = ../../../../data_sets/from_copter_1 ;
; path = ../../../../data_sets/tank_17_06_2021 ;
repeat = 1 ; Повторять воспроизведение из папки (1), не повторять (0).
num_fr_0 = 0 ; 15700 ; 3400 ; 9600 ; 7110 ; 3400 ; 2000 ; 3120 ; Номер первого фрейма.
num_fr_1 = 0 ; 3800 ; Номер последнего фрейма.

[recorder] ; Запись экрана
video_on = 1 ; вкл(1)/выкл(0) записи
save_frames_skip = 0 ; Запись фреймов, значение save_frames_skip соответствует количеству пропускаемых фреймов.
save_frames_prefix = 10000000 ; Префикс, с номера которого начинается запись кадров.
max_frames = 100000 ; Максимальное число записываемых фреймов.
path4frames = ../../../../data_sets/client_goen_saved_frames ; путь к фреймам
