[NETWORK0] ; OPEN
send_IP = 192.168.144.42 ; (OPEN)
client_in_port = 30000 ; 28666 ; Порт на клиенте для приема данных
goen_in_port = 30000 ; Порт на сервере для приема данных
ap_IP = 192.168.1.20 ;
ap_in_port = 22222 ; (OPEN)
valid_ap_step_decrease = 1e-1 ;
tm_xy_enable = 1 ;

[NETWORK] ; CLOSE
send_IP =  192.168.1.121 ; (CLOSE) (для сазан-борт)
client_in_port = 30000 ; 28666 ; Порт на клиенте для приема данных
goen_in_port = 30000 ; Порт на сервере для приема данных
ap_IP = 192.168.1.20 ; IP адрес автопилота АВАКС
ap_in_port = 22222 ; (CLOSE) порт приёма телеметрии автопилотом АВАКС
valid_ap_step_decrease = 1e-1 ; в случае потери трекера, валидность уменьшается на данное значение каждый кадр
tm_xy_enable = 1 ; передача

[main_settings] ; Выбор типа алгоритма:
device_id = 2 ; идентификатор устройства, с которого считываются кадры:
; 0 - FOLDER,
; 2 - WEBCAMERA,
; 12 - RTSP_SERVER_DEVICE
handle_flag = 1 ; возможность управлением захвата трека на текущем устройстве при велюченным управлении через ethernet

[tracking] ; Параметры для алгоритма TracShats:
min_max_Val = 74e-2 ; Трешхолд для матчинга шаблона (74e-2).
shift2 = 16e-3  ; Максимальный квадрат сдвига объекта между кадрами в пикселях (4e-3).
scaling = 0 ; Включить масштабирование (1) -- только для визуализации рамки, (2) -- учет масштабирования всем алгоритмом, (0) -- выключить.
k_renew_ok = 5 ; Период добавления эталонов в list_et в кадрах.
list_et_sz = 8 ; Максимальный размер списка эталонов list_et.
smooth_on = 1 ; Включение сглаживания координат цели (0 - выключено, 1 - сглаживание без влияния на алгоритм, 2 - сглаживание влияющее на алгоритм)
Polinom_size = 1 ; Степень полинома интерполяции для сглаживания.
deq_sz_min = 10 ; Минимальное для сглаживания число точек на траектории (не меньше 2), при deq_sz_min=0 сглаживание выключено.
validate_ext = -120 ; Минимальная степень валидации, ниже которой deinit.
zahvat_size_TV = 32 ; Размер полуширины стороны квадратной рамки захвата, при 0 - выделение рамки мышкой.
zahvat_size_TPV = 18 ;
max_fps = 1000 ; Максимально разрешенный fps, при его превышении - идёт задержка.

Vmin_TV = 150 ;     // min Speed (TV 45)
Vmax_TV = 200 ;     // max Speed (TV 200)
Vmin_TPV = 500 ;    // min Speed (TPV 180)
Vmax_TPV = 800 ;    // max Speed (TPV 400)
pos_azimuth_err = 0.38 ; 0.37;
pos_pitch_err = 1.1 ; 0.98;
Vx_dreyf = 38 ; step 0.01 * gradus/second  (0 - TPV, 10 - TV) (smaller - img move right)
Vy_dreyf = 100 ; step 0.01 * gradus/second  (0 - TPV, 60 - TV) (smaller - img move up)

[roll_pitch] ;
x1 = 16235 ; 17400 ;    Value_X Value_Y max value
x2 = -16400 ; -15666 ;  Value_X Value_Y min value
a_roll = 544366e-6 ;
b_roll0 = -1200 ; KREN
; TV = 180, TPV = -1050
a_pitch = 551555e-6 ;
b_pitch0 = -195 ; TANGAZH
; TV = -980, TPV = -30

[webcamera] ; dev2
webcamera_id_TV = 42 ; 2 - usb, 42 - mipi
webcamera_id_TPV = 60 ;
fps = 30 ; частота кадров камеры
backend_id = 1 ; (BACKEND_GSTREAMER = 0, BACKEND_V4L2 = 1, BACKEND_LATEST = 2)
rotate180 = 0 ; // переворот изображения

[RS_232_485] ;
rs232_speed = 115200 ;
rs485_speed = 115200 ;
show_command_interval = 50 ; количество кадров, в течение которых происходит индикация команды
SERIAL_PORT_RS232 = /dev/ttyUSB0 ;
SERIAL_PORT_RS485 = /dev/ttyUSB1 ;
SERIAL_PORT_RSTPV = /dev/ttyUSB2 ;
send_CMD_BLOCK_OFF = 1 ; 0 ; команда в конструкторе на снтятие блокировки двигателя (переход в режим курсовой стабилизации)



[rtp_sender] ; (CLOSE)
work = 1 ; ON(1)/OFF rtp server
mtu = 1280 ;
config_interval = 2 ;
gop = 2 ; интервал (сек) отправки ключевого кадра (i-frame)
bps = 2000 ; (CLOSE) битрейт (кбит/ cек)
codec = 264 ;
port = 8001 ; // IP для отправки видео (192.168.1.121 для сазан-борт)

[mat2rtsp] ; (OPEN) tool - checked only for Khadas
mtu = 1280 ;
config_interval = 2 ;
work = 1 ; ON(1)/OFF rtsp server
gop = 2 ; интервал (сек) отправки ключевого кадра (i-frame)
bps = 4000 ; kbit/s (OPEN)
codec = 264 ;
port_mountpoint = 8554/live/track0 ;

[logger]
lavel = 2 ; 0 - логирование отключено ; 1 - немелденное логгирование ; 2 - интервальное логгирование
destination = 0 ; 0 - логирование только в терминал ; 1 - запись логов только в файл ; 2 логирование в терминал + запись в файл
sleep_ms = 10000 ; интервал в мс
path_to_log = ../log ; путь к папке с логгами
max_number_of_log_folder = 2 ; максимальное количество папок с логами
log_current_time = 0 ; вкл/выкл логирования текущей даты и времени
log_execution_time = 1 ; вкл/выкл логирования времени выполнения программы
log_cpu_temperature = 1 ; вкл/выкл логирования времени температуры CPU
log_gpu_temperature = 0 ; вкл/выкл логирования времени температуры GPU

[demonstration_settings]
frame_show_width = 1920 ; ширина отображаемого кадра
demonstration_mode = 3 ; режим отображения: 1 - рамка захвата объекта, дополнительно: 2 - рамка поиска, 3 - статус трекера, 4 - размеры рамки объекта.
key_quit_handler = 47 ;

; Devices ;
[folder] ; dev0 (FOLDER)
way2init_rect = ../img_et/way2init_rect7.txt ; Путь к файлу с данными первоначального квадрата.
fps = 30 ;
frame_w = 0 ;
frame_h = 0 ;
; path = /home/grigoriy/data_sets/krym_kaspiy_07_2024/ship_kaspiy ;
; path = /home/grigoriy/data_sets/night_flyght_4_05_24 ;
path = ../../../../data_sets/from_copter_1 ;
; path = ../../../../data_sets/tank_17_06_2021 ;
repeat = 1 ; Повторять воспроизведение из папки (1), не повторять (0).
num_fr_0 = 0 ; 15700 ; 3400 ; 9600 ; 7110 ; 3400 ; 2000 ; 3120 ; Номер первого фрейма.
num_fr_1 = 0 ; 3800 ; Номер последнего фрейма.

[RTSP_SERVER] ; dev12
ip = 127.0.0.1 ;
port = 9999 ;
mountpoint = imx415 ;   any string
camera_id = 42 ;
width = 1920 ;          Устанавливается автоматически, если 0.
height = 1080 ;         Устанавливается автоматически, если 0.
codec = h264 ;          h265 rtsp working  tmml - wrong
bps = 4000000 ;         Target BPS (0 = auto calculate ~ 8000000)
fps = 30 ;
latency = 0 ;
name = sink ;
drop = true ;
emit_signals = true ;
sync = false ;
max_buffers = 2 ;
; play video on client :
; gst-launch-1.0 rtspsrc location=rtsp://192.168.1.79:port/mountpoint latency=0 ! queue ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! videoscale ! video/x-raw, width=1920, height=1080 ! autovideosink


[Kalman_settings]
dispersion_process = 25e-4 ; 2e-14 ; Ошибка измерений ;меньше значение, меньше доверие, лучше сглаживание больше значение, больше доверие, хуже сглаживание
dispersion_measurement = 8 ; Ошибка процесса ;ниже значение, более предсказуем процесс, небольшие ошибки выше значение, менее предсказуем процесс, большие ошибки
delta_t = 1e+1 ; 1e-5 Чем больше время, тем сильнее график для Калмана отстает в начале
speed_koef = 10 ; 3e7 ; 3e7 Коэффициент, на который умножается скорость после фильтра Калмана

[Kalman_velocity_settings]
dispersion_process = 1e-8 ; 2e-14 ; Ошибка измерений ;меньше значение, меньше доверие, лучше сглаживание больше значение, больше доверие, хуже сглаживание
dispersion_measurement = 16 ; Ошибка процесса ;ниже значение, более предсказуем процесс, небольшие ошибки выше значение, менее предсказуем процесс, большие ошибки
delta_t = 5e-3 ; 1e+1 ; Чем больше время, тем сильнее график для Калмана отстает в начале


[Kalman_angle_settings]
dispersion_process = 25e-4 ; 2e-14 ; Ошибка измерений ;меньше значение, меньше доверие, лучше сглаживание больше значение, больше доверие, хуже сглаживание
dispersion_measurement = 8 ; Ошибка процесса ;ниже значение, более предсказуем процесс, небольшие ошибки выше значение, менее предсказуем процесс, большие ошибки
delta_t = 1e+1 ; Чем больше время, тем сильнее график для Калмана отстает в начале

[MPU6050]
; 0 - getMotion6 - сырые данные с гироскопа,
; 1 - dmpGetGyro - обработанные DMP(digital motion processor) данные с гироскопа,
; 2 - v=da/dt производная значения угла по времени;
velocity_type = 0 ;
use_kalman = 1 ; подключаем ли фильт калмана к значениям скорости

[log_cmd]
path = ../log/ ;

[plot]
winname = Графики:синий-азимут. зелёный-крен, красный-тангаж. Толстые линии-угол [град], тонкие- скорость [град/с] ;
plot_w = 1920 ; размер окна вывода графика
plot_h = 1080 ;
num_f = 6 ; число функций y(x), выводимых на графике
x_min = 0 ; минимум, максимум и шаг аргумента
x_max = 10 ;
x_step = 1 ;
y_min = -180 ; минимум, максимум и шаг значения функции
y_max = 180 ;
y_step = 15 ;

